import "./styles/content.scss";
import "./styles/form.scss";
import "./styles/header.scss";
import "./styles/main.scss";
import "./scripts/storage";
import "./styles/sidebar.scss";
import "./scripts/dom";
import "./scripts/projects";
import "./scripts/todo";
